name: vegetation_health
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - atomicwrites=1.3.0
  - attrs=19.1.0
  - blas=1.0
  - bzip2=1.0.6
  - cftime=1.0.3.4
  - curl=7.64.0
  - hdf4=4.2.13
  - hdf5=1.10.4
  - intel-openmp=2019.1
  - jpeg=9b
  - libcurl=7.64.0
  - libgfortran=3.0.1
  - libnetcdf=4.6.1
  - mkl=2019.1
  - mkl_fft=1.0.10
  - mkl_random=1.0.2
  - more-itertools=6.0.0
  - netcdf4=1.4.2
  - numpy=1.16.2
  - numpy-base=1.16.2
  - pandas=0.24.1
  - pluggy=0.9.0
  - py=1.8.0
  - pytest=4.3.0
  - python-dateutil=2.8.0
  - pytz=2018.9
  - scikit-learn=0.20.2
  - scipy=1.2.1
  - six=1.12.0
  - xarray=0.11.3
  - ca-certificates=2019.3.9
  - certifi=2019.3.9
  - cycler=0.10.0
  - fire=0.1.3
  - freetype=2.9.1
  - kiwisolver=1.0.1
  - libpng=1.6.36
  - libssh2=1.8.0
  - matplotlib=3.0.3
  - matplotlib-base=3.0.3
  - openssl=1.1.1b
  - pyparsing=2.3.1
  - tqdm=4.31.1
  - appnope=0.1.0
  - backcall=0.1.0
  - cffi=1.12.2
  - decorator=4.3.2
  - ipykernel=5.1.0
  - ipython=7.3.0
  - ipython_genutils=0.2.0
  - jedi=0.13.3
  - jupyter_client=5.2.4
  - jupyter_core=4.4.0
  - krb5=1.16.1
  - libcxx=4.0.1
  - libcxxabi=4.0.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libsodium=1.0.16
  - ncurses=6.1
  - ninja=1.8.2
  - parso=0.3.4
  - pexpect=4.6.0
  - pickleshare=0.7.5
  - pip=19.0.3
  - prompt_toolkit=2.0.9
  - ptyprocess=0.6.0
  - pycparser=2.19
  - pygments=2.3.1
  - python=3.6.8
  - pyzmq=18.0.0
  - readline=7.0
  - setuptools=40.8.0
  - sqlite=3.26.0
  - tk=8.6.8
  - tornado=6.0.1
  - traitlets=4.3.2
  - wcwidth=0.1.7
  - wheel=0.33.1
  - xz=5.2.4
  - zeromq=4.3.1
  - zlib=1.2.11
  - pytorch=1.0.1
  - pip:
    - torch==1.0.1.post2
