name: vegetation_health
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - atomicwrites
  - attrs
  - blas
  - bzip2
  - cftime
  - curl
  - hdf4
  - hdf5
  - intel-openmp
  - jpeg
  - libcurl
  - libnetcdf=4.6.2
  - mkl
  - mkl_fft
  - mkl_random
  - more-itertools
  - netcdf4
  - numpy
  - numpy-base
  - pandas
  - pluggy
  - py
  - pytest
  - python-dateutil
  - pytz
  - scikit-learn
  - scipy
  - six
  - xarray
  - ca-certificates
  - certifi
  - cycler
  - fire
  - freetype
  - kiwisolver
  - libpng
  - libssh2
  - matplotlib
  - matplotlib-base
  - openssl
  - pyparsing
  - tqdm
  - backcall
  - cffi
  - decorator
  - ipykernel
  - ipython
  - ipython_genutils
  - jedi
  - jupyter_client
  - jupyter_core
  - krb5
  - libedit
  - libffi
  - libsodium
  - ncurses
  - ninja
  - parso
  - pexpect
  - pickleshare
  - pip
  - prompt_toolkit
  - ptyprocess
  - pycparser
  - pygments
  - python
  - pyzmq
  - readline
  - setuptools
  - sqlite
  - tk
  - tornado
  - traitlets
  - wcwidth
  - wheel
  - xz
  - zeromq
  - zlib
  - pytorch
  - appnope
  - libgfortran
  - libcxx
  - libcxxabi
  - pip:
    - torch
